language: node_js

node_js:
  - stable

install:
  - npm install --loglevel=error

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
